-- Insertion auteurs
INSERT INTO biblio_author (name, nationality, birth_date, biography, created_at, updated_at) VALUES
('Victor Hugo', 'Française', '1802-02-26', 'Écrivain et poète français célèbre.', NOW(), NOW()),
('Honoré de Balzac', 'Française', '1799-05-20', '', NOW(), NOW()),
('Émile Zola', 'Française', '1840-04-02', '', NOW(), NOW()),
('Marcel Proust', 'Française', '1871-07-10', '', NOW(), NOW()),
('Frankétienne', 'Haïtien', NULL, 'Auteur et poète haïtien renommé.', NOW(), NOW()),
('Edwidge Danticat', 'Haïtienne', NULL, 'Romancière haïtienne très connue.', NOW(), NOW()),
('Kettly Mars', 'Haïtienne', NULL, 'Écrivain haïtien contemporain.', NOW(), NOW()),
('René Depestre', 'Haïtien', '1926-08-29', '', NOW(), NOW()),
('Margaret Atwood', 'Canadienne', '1939-11-18', 'Romancière canadienne célèbre.', NOW(), NOW()),
('Alice Munro', 'Canadienne', '1931-07-10', '', NOW(), NOW()),
('Robertson Davies', 'Canadien', '1913-08-28', '', NOW(), NOW()),
('Michael Ondaatje', 'Canadien', '1943-09-12', '', NOW(), NOW()),
('George Sand', 'Française', '1804-07-01', '', NOW(), NOW()),
('Voltaire', 'Française', '1694-11-21', '', NOW(), NOW()),
('Albert Camus', 'Française', '1913-11-07', '', NOW(), NOW()),
('Gustave Flaubert', 'Française', '1821-12-12', '', NOW(), NOW()),
('Jean-Paul Sartre', 'Française', '1905-06-21', '', NOW(), NOW()),
('Antoine de Saint-Exupéry', 'Française', '1900-06-29', '', NOW(), NOW()),
('Guy de Maupassant', 'Française', '1850-08-05', '', NOW(), NOW()),
('Alexandre Dumas', 'Française', '1802-07-24', '', NOW(), NOW()),
('Simone de Beauvoir', 'Française', '1908-01-09', '', NOW(), NOW()),
('Molière', 'Française', '1622-01-15', '', NOW(), NOW()),
('Jules Verne', 'Française', '1828-02-08', '', NOW(), NOW()),
('Jacques Roumain', 'Haïtien', NULL, '', NOW(), NOW()),
('Katia D. Ulysse', 'Haïtienne', NULL, '', NOW(), NOW()),
('Yann Martel', 'Canadien', '1963-06-08', '', NOW(), NOW()),
('Lucy Maud Montgomery', 'Canadienne', '1874-11-30', '', NOW(), NOW()),
('Carol Shields', 'Canadienne', '1935-06-02', '', NOW(), NOW()),
('David Adams Richards', 'Canadien', '1950-02-17', '', NOW(), NOW()),
('Anne Michaels', 'Canadienne', '1958-01-13', '', NOW(), NOW()),
('Jean Price-Mars', 'Haïtien', '1876-11-06', 'Anthropologue, diplomate et homme politique haïtien, auteur d\'œuvres majeures sur la culture haïtienne.', NOW(), NOW()),
('Frédéric Marcelin', 'Haïtien', '1848-03-18', 'Écrivain et homme politique haïtien, connu pour ses romans et ses contributions culturelles.', NOW(), NOW()),
('Dantès Bellegarde', 'Haïtien', '1877-05-15', 'Historien, diplomate et homme politique haïtien avec plusieurs publications sur l\'histoire d\'Haïti.', NOW(), NOW()),
('Louverture Cleary', 'Haïtien', NULL, 'Homme politique et auteur haïtien, spécialisé dans la réflexion politique et sociale.', NOW(), NOW()),
('Pierrot Dominique', 'Haïtien', '1950-04-20', 'Politicien haïtien et écrivain, connu pour ses analyses politiques.', NOW(), NOW()),
('Gérard Pierre-Charles', 'Haïtien', '1935-01-01', 'Économiste et homme politique haïtien, auteur d\'ouvrages sur le développement social et économique d\'Haïti.', NOW(), NOW()),
('Lorimer Denis', 'Haïtien', '1895-09-19', 'Anthropologue, écrivain et homme politique, contributeur majeur à la culture haïtienne.', NOW(), NOW()),
('Jean Dominique', 'Haïtien', '1930-01-01', 'Journaliste, écrivain et activiste politique haïtien, voix majeure de la démocratie.', NOW(), NOW()),
('Henri Christophe', 'Haïtien', '1767-10-06', 'Figure historique haïtienne, roi d’Haïti et auteur d’édits politiques.', NOW(), NOW()),
('Jacques Stephen Alexis', 'Haïtien', '1922-04-21', 'Romancier et militant politique haïtien, auteur influent.', NOW(), NOW());


-- Insertion éditeurs
INSERT INTO biblio_publisher (publisher_name, address, phone, email, created_at) VALUES
('Hachette Livre', 'France', '', '', NOW()),
('Éditions Gallimard', '5 rue Sébastien Bottin, Paris, France', '', '', NOW()),
('Bayard Éditions', 'France', '', '', NOW()),
('Actes Sud', 'France', '', '', NOW()),
('Éditions Fardin', 'Port-au-Prince, Haïti', '', '', NOW()),
('JEBCA Éditions', 'Haïti', '', '', NOW()),
('C3 Éditions', 'Port-au-Prince, Haïti', '', '', NOW()),
('LEGS ÉDITION', 'Port-au-Prince, Haïti', '', '', NOW()),
('Éditions Mémoire d\'Encrier', 'Montreal, Canada', '', '', NOW()),
('Annick Press', 'Canada', '', '', NOW()),
('ECW Press', 'Canada', '', '', NOW()),
('Harbour Publishing', 'Canada', '', '', NOW()),
('Heritage House Publishing', 'Canada', '', '', NOW()),
('Éditions Mémoires', 'Haïti', '', '', NOW()),
('Presses Nationales d\'Haïti', 'Haïti', '', '', NOW()),
('Éditions Caraïbes', 'Port-au-Prince, Haïti', '', '', NOW());


-- Insertion catégories
INSERT INTO biblio_category (category_name, description, created_at, updated_at) VALUES
('Littérature française', 'Œuvres littéraires en langue française, comprenant romans, poésie, théâtre et essais produits par des auteurs français ou en langue française.', NOW(), NOW()),
('Littérature haïtienne', 'Œuvres littéraires issues d\'auteurs haïtiens, mettant en lumière la culture, l\'histoire et les réalités d\'Haïti.', NOW(), NOW()),
('Littérature canadienne', 'Œuvres littéraires produites par des auteurs canadiens, en français ou en anglais, reflétant la diversité culturelle du Canada.', NOW(), NOW()),
('Roman historique', 'Romans qui racontent des événements historiques, mêlant souvent faits réels et intrigue fictionnelle.', NOW(), NOW()),
('Roman contemporain', 'Romans situés dans des contextes modernes, traitant de thèmes actuels et sociaux.', NOW(), NOW()),
('Poésie', 'Œuvres exprimant des émotions et des idées en vers, utilisant différentes formes et styles poétiques.', NOW(), NOW()),
('Essais', 'Textes analytiques ou critiques traitant d\'un sujet spécifique, souvent d\'ordre culturel, social ou philosophique.', NOW(), NOW()),
('Jeunesse', 'Œuvres littéraires destinées à un public jeune, incluant albums, romans, et ouvrages didactiques.', NOW(), NOW()),
('Science-fiction', 'Œuvres exploitant des concepts scientifiques et technologiques imaginaires pour explorer des futurs possibles ou des univers alternatifs.', NOW(), NOW()),
('Policier et suspense', 'Romans centrés sur des enquêtes criminelles, des mystères et des intrigues à suspense.', NOW(), NOW()),
('Bande dessinée', 'Œuvres narratives mêlant images et texte, couvrant un large éventail de genres et de styles.', NOW(), NOW()),
('Théâtre', 'Textes destinés à être joués sur scène, comprenant pièces classiques et contemporaines.', NOW(), NOW()),
('Philosophie', 'Œuvres traitant de questions fondamentales sur l\'existence, la connaissance, la morale et la raison.', NOW(), NOW()),
('Histoire', 'Ouvrages documentant et analysant des événements, des époques et des personnages historiques.', NOW(), NOW()),
('Biographies et mémoires', 'Récits de vie de personnes réelles, offrant un éclairage personnel sur des parcours divers.', NOW(), NOW()),
('Documentation professionnelle', 'Ouvrages techniques et spécialisés destinés aux professionnels de différents secteurs.', NOW(), NOW()),
('Sciences sociales', 'Études et analyses des sociétés humaines, incluant sociologie, anthropologie et économie.', NOW(), NOW()),
('Arts visuels', 'Publications sur la peinture, la sculpture, la photographie et autres formes d\'arts visuels.', NOW(), NOW()),
('Musique et arts sonores', 'Ouvrages dédiés à la musique, à la composition et aux arts sonores.', NOW(), NOW()),
('Droit et législation', 'Textes légaux, codes et analyses juridiques pour la pratique et l\'étude du droit.', NOW(), NOW()),
('Économie', 'Ouvrages et études traitant de la production, distribution et consommation des biens et services, ainsi que des politiques économiques.', NOW(), NOW()),
('Mathématiques', 'Travaux et manuels sur les mathématiques pures et appliquées, incluant algèbre, géométrie, calcul et statistiques.', NOW(), NOW()),
('Comptabilité', 'Documents et guides pratiques sur les principes, méthodes et pratiques comptables en entreprise et gestion financière.', NOW(), NOW()),
('Science politique', 'Études et analyses des systèmes politiques, théories, institutions et comportements politiques.', NOW(), NOW()),
('Gestion et management', 'Publications sur les pratiques de gestion, leadership, organisation et stratégies d\'entreprise.', NOW(), NOW()),
('Informatique', 'Ouvrages sur les technologies de l\'information, programmation, réseaux, sécurité informatique et systèmes.', NOW(), NOW()),
('Droit international', 'Textes et références sur les lois et régulations internationales, accords et conventions.', NOW(), NOW()),
('Santé publique', 'Travaux sur la médecine préventive, politiques de santé, épidémiologie et gestion de la santé.', NOW(), NOW()),
('Environnement et écologie', 'Études portant sur les sciences de l\'environnement, la conservation et les politiques écologiques.', NOW(), NOW()),
('Éducation et pédagogie', 'Ouvrages sur les méthodes d\'enseignement, didactique et développement pédagogique.', NOW(), NOW());



