# Generated by Django 5.1.1 on 2025-12-12 02:51

import biblio.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblio', '0004_book_cover_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='cover_url',
        ),
        migrations.AddField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to=biblio.models.book_cover_path),
        ),
    ]
